apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 03-cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:  
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/bogd/demo-k8s
    path: app_setup/cert-manager/overlays/dr1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
