apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system 
resources: 
- https://raw.githubusercontent.com/metallb/metallb/v0.14.4/config/manifests/metallb-native.yaml
- bgpadvertisement.yaml
- bgppeer.yaml
