apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:  
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://bogd/demo-k8s.git
    path: app_setup/webapp/overlays/prod
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 