apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 01-metallb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:  
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/bogd/demo-k8s.git
    path: app_setup/metallb/overlays/prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
